---
- name: create oracle database
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ora_user_env}}"
  command: "{{ oracle_base }}/createDB.sh {{ora_user_env.ORACLE_SID}} {{ora_user_env.ORACLE_PDB}}"
  args:
      creates: "{{ oracle_base }}/oradata/{{ora_user_env.ORACLE_SID}}"
- name: set oracle database environment
  blockinfile:
    dest: /home/{{ oracle_user }}/.bashrc
    block: |
      export ORACLE_SID={{ ora_user_env.ORACLE_SID }}
      export ORACLE_PDB={{ ora_user_env.ORACLE_PDB }}
