---
- name: create oracle database
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ora_user_env}}"
  command: "{{ oracle_base }}/createDB.sh"
  args:
      creates: "{{ oracle_base }}/oradata/{{ora_user_env.ORACLE_SID}}"
